export const colors = {
  primary: '#0A1628',
  primaryMid: '#1B3A6B',
  accent: '#00C2A8',
  accentLight: '#E6FAF8',
  accentDark: '#008F7A',
  emergency: '#DC2626',
  emergencyLight: '#FEF2F2',
  urgent: '#D97706',
  urgentLight: '#FFFBEB',
  mild: '#059669',
  mildLight: '#ECFDF5',
  info: '#3B82F6',
  infoLight: '#EFF6FF',
  surface: '#FFFFFF',
  background: '#F8FAFC',
  border: '#E2E8F0',
  borderStrong: '#CBD5E1',
  textPrimary: '#0F172A',
  textSecondary: '#64748B',
  textTertiary: '#94A3B8',
  textOnAccent: '#FFFFFF',
  textOnEmergency: '#FFFFFF',
  drLucasBubble: '#0A1628',
  drLucasText: '#FFFFFF',
  userBubble: '#00C2A8',
  userText: '#FFFFFF',
  canvas: '#F8FAFC',
  surfaceSoft: '#F1F5F9',
  surfaceCard: '#FFFFFF',
  surfaceCreamStrong: '#CBD5E1',
  hairline: '#E2E8F0',
  hairlineSoft: '#E2E8F0',
  ink: '#0F172A',
  body: '#0F172A',
  bodyStrong: '#0F172A',
  muted: '#64748B',
  mutedSoft: '#94A3B8',
  primaryActive: '#1B3A6B',
  primaryDisabled: '#CBD5E1',
  onPrimary: '#FFFFFF',
  surfaceDark: '#0A1628',
  surfaceDarkElevated: '#1B3A6B',
  surfaceDarkSoft: '#1B3A6B',
  onDark: '#FFFFFF',
  onDarkSoft: '#94A3B8',
  accentTeal: '#00C2A8',
  accentAmber: '#D97706',
  success: '#059669',
  warning: '#D97706',
  error: '#DC2626',
  surfaceMuted: '#F8FAFC',
  text: '#0F172A',
  textMuted: '#64748B',
  primarySoft: 'rgba(10,22,40,0.12)',
  danger: '#DC2626',
  dangerSoft: '#FEF2F2',
  warningSoft: '#FFFBEB',
  successSoft: '#ECFDF5',
};

export const spacing = {
  xxs: 4,
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
};

export const radius = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 24,
  full: 9999,
  pill: 9999,
};

export const typography = {
  h1: { fontSize: 28, fontWeight: '700' as const, letterSpacing: -0.5, color: colors.textPrimary },
  h2: { fontSize: 22, fontWeight: '700' as const, letterSpacing: -0.3, color: colors.textPrimary },
  h3: { fontSize: 17, fontWeight: '600' as const, color: colors.textPrimary },
  body: { fontSize: 15, fontWeight: '400' as const, lineHeight: 22, color: colors.textPrimary },
  bodySmall: { fontSize: 13, fontWeight: '400' as const, lineHeight: 18, color: colors.textSecondary },
  caption: {
    fontSize: 11,
    fontWeight: '600' as const,
    color: colors.textTertiary,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
  },
  label: { fontSize: 13, fontWeight: '600' as const, color: colors.textSecondary },
  authBrand: { fontSize: 32, fontWeight: '700' as const, letterSpacing: -0.6, color: colors.primary },
  authTagline: { fontSize: 14, fontWeight: '400' as const, lineHeight: 22, color: colors.textSecondary },
  authWelcome: { fontSize: 22, fontWeight: '700' as const, letterSpacing: -0.3, color: colors.textPrimary },
  authLead: { fontSize: 15, fontWeight: '400' as const, lineHeight: 22, color: colors.textSecondary },
  authCta: { fontSize: 15, fontWeight: '600' as const },
  authSecondaryCta: { fontSize: 15, fontWeight: '600' as const, color: colors.textPrimary },
  otpDigit: { fontSize: 22, fontWeight: '600' as const, color: colors.textPrimary },
};

export const fonts = {
  display: 'System',
  displayRegular: 'System',
  body: 'System',
  bodyRegular: 'System',
  bodyMedium: 'System',
  bodySemiBold: 'System',
  bodyBold: 'System',
} as const;
